# This workflow will run tests, build and deploy to VPS
# It will run on release events

name: Deploy

on:
  release:
    types: [published]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CI
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm i
      - run: npm run build --if-present
      - run: npm test

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            echo ${{ secrets.HOST }} ${{ secrets.USERNAME }} ${{ secrets.key }}
            echo "Deploying to VPS..."
            echo ls
            echo "Moving to project directory ${{ github.event.repository.name }}"
            cd /${{ github.event.repository.name }}
            echo "Pulling changes from GitHub"
            git pull
            echo "Installing dependencies"
            npm i
            echo "Building project"
            npm run build
            echo "Restarting pm2 process"
            pm2 restart ${{ github.event.repository.name }}
            echo "Deployment complete"
            
