# This workflow will run tests, build and deploy to VPS
# It will run on release events

name: Deploy

on:
  release:
    types: [published]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CI
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm i
      - run: npm run build --if-present
      - run: npm test

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.USERNAME }}/${{ github.event.repository.name }}
            git pull
            npm i
            npm run build
            pm2 restart ${{ github.event.repository.name }}